---

name: Install Google Chrome Repos
  yum_repository:
    name: google-chrome
    description: Google Chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub


name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: latest
  become: true
