---

- hosts: localhost
  user: mburket

  vars_files:
    - group_vars/all.yml
  
  roles: 
    - rpm_fusion_free
    - rpm_fusion_nonfree
    - common
    - dev
    - postgres
    - docker
    - rbenv
    - iscore
    - latex
    - ssh
    - zfs
    - virtualization
    - gnome
    - slack
    - google-chrome
    - php
    - dot-net-core


