---

- name: Install the 'virtualization' package group
  become: yes
  dnf:
    name: '@virtualization'
    state: present


- name: Install vfio
  become: yes
  file:
    content: "options vfio-pci ids=10de:13c2,10de:0fbb"
    dest: /etc/modprobe.d/vfio.conf
    force: no
    root: root
    group: root
    force: no


- name: Nested KVM
  become: yes
  lineinfile:
    regexp: '^#options kvm_intel nested=1'
    line: 'options kvm_intel nested=1'

- name: Install vfio dracut 
  become: yes
  copy:
    content: 'add_drivers+="vfio vfio_iommu_type1 vfio_pci vfio_virqfd"'
    dest: /etc/dracut.conf.d/vfio.conf
    force: no
    group: root
    owner: root

- name: dracut regen
  - become: true
  - command: dracut -f

- name: Add immou to kvm boot
  become: yes
  lineinfile:
    state: present
    dest: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*iommu)\"[^\"]+)(\".*)'
    backrefs: yes
    line: '\1 iommu=1 intel_iommu=on kvm-intel.nested=1 rd.driver.pre=vfio-pci\2'

- name: Regenerate GRUB2 config
  become: yes
  command: grub2-mkconfig -o /etc/grub2-efi.cfg
