---

- name: upgrade all packages
  become: yes
  dnf:
    name: "*"
    state: latest

- name: Install common packages
  become: true
  dnf:
    name={{ item }} state=installed
  with_items:
    - gnome-tweak-tool
    - wireshark-qt
    - nmap
    - irssi
    - cowsay
    - tmux
    - sshfs
    - iotop
    - iftop
    - powertop
    - vlc
    - audacity
    - conky
    - telegram-desktop
    - strace
    - duplicity
    - libselinux-python

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    clone: yes
    update: yes
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  sudo: no

- name: Set my shell to zsh
  become: yes
  user:
    name: mburket
    shell: /bin/zsh

- name: Add yser
  user:
    name: {{ user }}
    groups: wireshark
    append: yes
