---

- name: Install dev packages
  become: true
  dnf:
    name={{ item }} state=installed
  with_items:
    - gnome-builder
    - vim
    - '@Development tools'
    - zsh
    - curl
    - wget
    - git
    - sysstat
    - cloc
    - astyle
    - mercurial
    - cmake
    - make
    - autoconf
    - automake
    - zlib
    - zlib-devel
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - "@c-development"
    - nodejs
- name: Create code folder
  file: 
    path: "/home/{{user}}/code"
    state: directory
    mode: 0755
