---

- name: Install postgres
  become: true
  dnf:
    name={{ item }} state=installed
  with_items:
    - postgresql-server
    - postgresql-contrib
    - postgresql-devel

# - name: Postgres Setup
#   become: true
#   command: /usr/bin/postgresql-setup --initdb

# - name:
#   become: yes
#   become_user: postgres
#   command: "createuser {{ user }} --superuser"

- name:
  become: yes
  become_user: postgres
  command: "createdb {{ user }} -O {{ user }}"
  

- name: Start postgresql on start up
  become: yes
  systemd:
    name: postgresql
    enabled: yes
    masked: no
    state: started


